### ISSUE TITLE
Menu hardly readable

### ISSUE THREAD

**Issue by nomad71** [gitskarios/Gitskarios#135]
http://imgur.com/55JTPXE

The screenshot shows the menu when opened by the hardware menu-button. White on light grey is hardly readable - especially in broad daylight ... although the last one obviously depends on my potatophone as well ...

**Comment by alorma** [comment]
Ops!

Which phone do you have?

**Comment by nomad71** [comment]
Samsung Galaxy S3 mini (GT-I8190)

... still working and useful but not exactly top gear.

**Comment by alorma** [comment]
Should be fixed in the last update

**Comment by nomad71** [comment]
http://imgur.com/0oFvkDw

Just updated - still not optimal ...

Should've mentioned that I'm using CM 11 as ROM. Sorry!

**Comment by alorma** [comment]
Should be fixed thanks to @vanogrid in Pull Request #154 

@nomad71 Will you check and give feedback in the next release, please?

**Comment by nomad71** [comment]
fixed! n1 & thx!
