### ISSUE TITLE
View pull request conversations

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#163]
When inline comments are made as part of a pull request, there is not a way to review the dialog via the app.

**Comment by alorma** [comment]
you can see the commits comments.

But i plan to add what you said, just not started yet

**Comment by mmoayyed** [comment]
Understood, thank you.

**Comment by alorma** [comment]
Hi @mmoayyed , can you provide an example for that?

**Comment by mmoayyed** [comment]
Try this please https://github.com/Jasig/cas/pull/993

I was looking at it this morning, and my experience is not the same as that of github's conversations.

**Comment by alorma** [comment]
Hi @mmoayyed i have a preview version of this feature.

It will be really great if you can check it from here: https://github.com/gitskarios/Gitskarios/releases/tag/v.2.5.0.2

**Comment by mmoayyed** [comment]
thanks very much. I honestly don't know how to test it :) I am simply running the app on a nexus 4. is there an update channel setting I could subscribe to, to get gets releases? in which case I'd be happy to test it.

**Comment by mmoayyed** [comment]
Ah ic, so it's just an APK. OK. I can work with that. Stay tuned.

**Comment by alorma** [comment]
Done, you can test it in last release

**Comment by mmoayyed** [comment]
this is still not fixed. I don't see inline comments on the pull request. only what's submitted to the pull itself. can provide an example but should be easy to duplicate. running the latest version on Google Play.

**Comment by mmoayyed** [comment]
https://github.com/Jasig/cas/pull/1076 as an example

**Comment by alorma** [comment]
For now i will not modify the PullRequest screen.

API doesn't provide with that information in a easy way, and try to duplicate that example requires too many requests to API and that's not good for battery life.

You can see the comments inside commit in commit screen

**Comment by mmoayyed** [comment]
I understand. As an alternative, would an option make sens to allow the user to do that sort of thing? to actively accept battery drains and the cost of API requests?

**Comment by mmoayyed** [comment]
>You can see the comments inside commit in commit screen

Problem with this is, I don't know if there are comments. Cant tell unless I go into the commit which is less than ideal. Maybe an icon or something to tell me that comments do exist and I should dive in?
