### ISSUE TITLE
App loop crashing

### ISSUE THREAD

**Issue by SkyzohKey** [gitskarios/Gitskarios#355]
Hey guys, here is a weird issue that makes me unable to use GitSkarios after login. I tried to reinstall but this doesn't work.

```
Build version: 2.8.2 
Build date: 2016-02-14 13:03:12 
Current date: 2016-02-16 01:02:30 
Device: WIKO PULP FAB 4G 

Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
    at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
    at com.alorma.timeline.RoundTimelineView.transform(RoundTimelineView.java:63)
    at com.alorma.timeline.RoundTimelineView.drawBitmap(RoundTimelineView.java:46)
    at com.alorma.timeline.TimelineView.onDraw(TimelineView.java:214)
    at android.view.View.draw(View.java:15239)
    at android.view.View.buildDrawingCacheImpl(View.java:14485)
    at android.view.View.buildDrawingCache(View.java:14347)
    at android.view.View.updateDisplayListIfDirty(View.java:14156)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.View.draw(View.java:14967)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
    at android.view.View.updateDisplayListIfDirty(View.java:14170)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.View.draw(View.java:14967)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
    at android.view.View.draw(View.java:15242)
    at android.view.View.updateDisplayListIfDirty(View.java:14175)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
    at android.view.View.updateDisplayListIfDirty(View.java:14135)
    at android.view.View.getDisplayList(View.java:14197)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2548)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2364)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1994)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5903)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
    at android.view.Choreographer.doCallbacks(Choreographer.java:586)
    at android.view.Choreographer.doFrame(Choreographer.java:556)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

**Comment by alorma** [comment]
Hey, yes i notcied this bug. I will fix it soon

**Comment by alorma** [comment]
Fixed

**Comment by toXel** [comment]
So I still have this error with the new version. I did a complete reinstall of the app:

```
Build version: 2.8.3 
Build date: 2016-02-16 12:18:16 
Current date: 2016-02-16 16:18:07 
Device: Lge LG-D802 

Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
    at android.graphics.Bitmap.createBitmap(Bitmap.java:832)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:776)
    at com.alorma.timeline.RoundTimelineView.transform(RoundTimelineView.java:67)
    at com.alorma.timeline.RoundTimelineView.drawBitmap(RoundTimelineView.java:47)
    at com.alorma.timeline.TimelineView.onDraw(TimelineView.java:214)
    at android.view.View.draw(View.java:16208)
    at android.view.View.buildDrawingCacheImpl(View.java:15505)
    at android.view.View.buildDrawingCache(View.java:15366)
    at android.view.View.updateDisplayListIfDirty(View.java:15186)
    at android.view.View.draw(View.java:15978)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    at android.view.View.updateDisplayListIfDirty(View.java:15200)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15165)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:606)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5466)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by alorma** [comment]
That's not cool :(

I will check later, thanks

**Comment by alorma** [comment]
Hey @ hrules6872 can you check it please?

**Comment by alorma** [comment]
Hey @hrules6872 can you check it please?

**Comment by hector6872** [comment]
It seems a known Glide issue with GIF images. I'll look into it ASAP :)

**Comment by hector6872** [comment]
I was going to work on this issue when I just see this commit https://github.com/alorma/TimelineView/commit/ddea1a14ab8b5e73a4977ea4abbbbdcc244acc0e so, you should close this issue I guess :)

**Comment by alorma** [comment]
Someone says it's still happening at 2.8.3

**Comment by hector6872** [comment]
Here we go! https://github.com/alorma/TimelineView/pull/4

**Comment by alorma** [comment]
Merged! I will generate a version tomorrow

**Comment by alorma** [comment]
Fixed at 2.8.4

**Comment by alorma** [comment]
@SkyzohKey how it works with the 2.8.4 version?

**Comment by SkyzohKey** [comment]
@alorma Works nice, thanks for the quick fix. :)
