### ISSUE TITLE
Visual Corruption on Pull Request Files View

### ISSUE THREAD

**Issue by rummik** [gitskarios/Gitskarios#361]
Reproduction steps:
- Look at a pull request
- View files changed/added in the request
- Scroll up and down

https://goo.gl/photos/kJWjPrEqU4SVr48F9

**Comment by alorma** [comment]
Hi.

Yes i noticied that, it also happens on commit files view.

I will study it

**Comment by taltstidl** [comment]
@alorma This is probably because your `CardView` has the same elevation as the `AppBarLayout` (4dp). Decreasing the card elevation to 2dp, as is recommended in the Material Design guidelines, should fix the issue.

**Comment by tdkl** [comment]
Was this addressed yet ? I still see the same issue in the latest Play release.

**Comment by alorma** [comment]
No :(
I didn't had time to check it :s
