### ISSUE TITLE
Refreshing lists causes duplicate items

### ISSUE THREAD

**Issue by farbodsz** [gitskarios/Gitskarios#406]
When refreshing lists, such as the Events stream, items in the list appear to be duplicated.

I am opening this as it is still an issue in the latest version of the app (at the time of writing, I believe this is 2.10.11).

Similar issues to this have been reported before:
- #337 
- #357 
- #380 
- #403 

...all of which are still present in the latest version of the app, as far as I am aware.

**Comment by alorma** [comment]
Thanks.

I'm aware of that, and i will try this as soon as posible

**Comment by alorma** [comment]
Hi.

I guess it's fixed now, could you check?

**Comment by farbodsz** [comment]
@alorma Sure - do I need to update via the Play Store, or in another way? (I hope this isn't a silly question!)

**Comment by alorma** [comment]
Yes, play store version 2.11.0

(with an awesome new feature in gists)

**Comment by farbodsz** [comment]
Thanks for the quick reply and update, @alorma .

**The issue with Gists duplicating has been resolved** (originally issue #337 and #380), and I'm also loving the new layout for Gists (however it would also be nice to be able to open a particular file by clicking on the file name on a Gist item :))

**The Events stream still duplicates list items** when refreshing (swiping down).

There is also **another duplication issue**:
- Go to the 'Repositories' screen (via the nav drawer)
- Go to the 'About' screen (via the nav drawer)
- Go back to 'Repositories'
- The list of repositories seems to be infinite (duplicated)

Overall, the update is great, fixes bugs, and I really like the new way of viewing Gists. But there are still some bugs.

**Comment by splendidbits** [comment]
I am also still getting the duplicated infinite items too on the repositories fragment.

**Comment by alorma** [comment]
I will make the items clickable, but it needs a bit of work. :)

**Comment by alorma** [comment]
Fixed on v.2.12.0

**Comment by alorma** [comment]
Could you guys please check in 2.12.0?

**Comment by farbodsz** [comment]
This seems to be fixed now!

Thank you!

**Comment by alorma** [comment]
Great!
